# Generated by Django 6.0.2 on 2026-02-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_userprofile_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_shop',
            field=models.BooleanField(default=True),
        ),
    ]
