# Generated by Django 6.0.1 on 2026-02-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Distributor', 'Distributor'), ('Admin', 'Admin')], default='Customer', max_length=20),
        ),
    ]
